// Direction Karel can face
export type Direction = 'north' | 'south' | 'east' | 'west'

// Grid position (0-indexed, origin top-left)
export type Position = { x: number; y: number }

// Wall on a cell edge. A wall at {x:3, y:5, side:'east'} blocks movement
// from (3,5) east AND from (4,5) west (bidirectional)
export type Wall = { x: number; y: number; side: 'north' | 'east' | 'south' | 'west' }

// Complete world state (immutable — every operation returns a new WorldState)
export type WorldState = {
  width: number
  height: number
  karel: {
    position: Position
    direction: Direction
  }
  beepers: Position[]   // Beeper locations on the grid
  walls: Wall[]         // Internal walls (grid boundary is implicit)
}

// Task definition loaded from tasks.json
export type TaskDefinition = {
  id: string
  level: 1 | 2 | 3
  title: string
  description: string
  hint?: string
  grid: {
    walls: Wall[]
    beepers: Position[]
  }
  karel: {
    position: Position
    direction: Direction
  }
  goal: {
    karel?: {
      position?: Position
      direction?: Direction
    }
    beepers?: Position[]
  }
}

// === AST types (generated by Blockly code generator, consumed by interpreter) ===

export type CommandName = 'moveForward' | 'turnLeft' | 'turnRight' | 'turnAround' | 'pickBeeper' | 'dropBeeper'

export type ConditionName = 'onBeeper' | 'beeperAhead' | 'frontIsClear' | 'leftIsClear' | 'rightIsClear'

export type CommandNode = { type: 'command'; name: CommandName }
export type RepeatNode = { type: 'repeat'; count: number; body: ASTNode[] }
export type IfElseNode = { type: 'ifElse'; condition: ConditionName; then: ASTNode[]; else: ASTNode[] }

export type ASTNode = CommandNode | RepeatNode | IfElseNode

export type Program = ASTNode[]

// === Execution types ===

export type Action = {
  command: CommandName
  previousState: WorldState
  resultState: WorldState
  error?: string
}

export type ExecutionResult = {
  actions: Action[]
  finalState: WorldState
  error?: string
}

// === Validation types ===

export type ValidationResult = {
  success: boolean
  details: string
}

// === Progress types ===

export type ProgressState = {
  solved: string[]          // Array of solved task IDs
  unlockedLevel: 1 | 2 | 3
  allUnlocked: boolean      // Betreuer-Freischaltung via Ctrl+Shift+U
}

// === Feedback types ===

export type FeedbackType = 'success' | 'failure' | 'error' | 'levelComplete'

export type FeedbackState = {
  type: FeedbackType
  message: string
  level?: number  // For levelComplete feedback
} | null

// === Speed type ===

export type SpeedSetting = 'slow' | 'normal' | 'fast'
